data:
  batch_size: 128
  crop_size: 224
  image_folder: flowers102/
  lmdb_path: flowers102.lmdb
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
  root_path: data/flowers102.lmdb
logging:
  folder: logs/evaluation/flowers102/full_in1k_vith14_ep200/
  write_tag: jepa_eval
meta:
  dataset_name: flowers102
  model_name: vit_huge
  read_checkpoint: logs/downstream/flowers102/full_in1k_vith14_ep200/jepa_full-latest.pth.tar
model:
  patch_size: 14
