data:
  batch_size: 128
  crop_size: 224
  image_folder: pets/
  lmdb_path: pets.lmdb
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
  root_path: data/pets.lmdb
logging:
  folder: logs/evaluation/pets/full_in1k_vith14_ep200_cosine/
  write_tag: jepa_eval
meta:
  dataset_name: pets
  model_name: vit_huge
  read_checkpoint: logs/downstream/pets/full_in1k_vith14_ep200_cosine/jepa_full-latest.pth.tar
model:
  patch_size: 14
