data:
  batch_size: 128
  crop_size: 224
  image_folder: stanford_cars/
  lmdb_path: stanford_cars.lmdb
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
  root_path: data/stanford_cars.lmdb
logging:
  folder: logs/evaluation/stanford_cars/full_in1k_vith14_ep200/
  write_tag: jepa_eval
meta:
  dataset_name: stanford_cars
  model_name: vit_huge
  read_checkpoint: logs/downstream/stanford_cars/full_in1k_vith14_ep200/jepa_full-latest.pth.tar
model:
  patch_size: 14
