data:
  batch_size: 32
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: caltech101/
  lmdb_path: caltech101.lmdb
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
  root_path: data/caltech101.lmdb
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: logs/downstream/caltech101/full_in1k_vith14_ep200/
  write_tag: jepa_full
meta:
  dataset_name: caltech101
  strategy: full
  copy_data: false
  load_checkpoint: true
  model_name: vit_huge
  read_checkpoint: logs/official/in1k_vith14_ep300/IN1K-vit.h.14-300e.pth.tar
  use_bfloat16: true
model:
  patch_size: 14
optimization:
  epochs: 200
  scheduler_type: linear
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
