data:
  batch_size: 128
  crop_size: 224
  image_folder: cub200/
  lmdb_path: cub200.lmdb
  num_workers: 1
  prefetch_factor: 1
  pin_mem: true
  root_path: data/cub200.lmdb
logging:
  folder: logs/evaluation/cub200/linear_in1k_vith14_ep200/
  write_tag: jepa_eval
meta:
  dataset_name: cub200
  model_name: vit_huge
  read_checkpoint: logs/downstream/cub200/linear_in1k_vith14_ep200/jepa_linear-latest.pth.tar
model:
  patch_size: 14
